### ISSUE TITLE
Osctrl includes filepaths during compilation

### ISSUE THREAD

**Issue by CptOfEvilMinions** [jmpsec/osctrl#224]
During runtime osctrl outputs paths from the system it was compiled on:

osctrl admin error log:
```
2022/03/08 05:44:42 /Users/<username>/osctrl/settings/settings.go:276 ecord not found
```

osctrl cli error log:
```
./osctrl-cli-linux-amd64.bin -D osctrl_db.json env secret --name "dev"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6291c5]

goroutine 1 [running]:
github.com/jmpsec/osctrl/environments.(*Environment).Get(_, {_, _})
	/Users/<username>/osctrl/environments/environments.go:102 +0x105
main.secretEnvironment(0xc0001d0f60)
	/Users/<username>/osctrl/cli/environment.go:291 +0x108
```

**Comment by javuto** [comment]
I believe those paths are generated on execution time, so they are not in the binary.
