### ISSUE TITLE
osctrl-cli from docker container doesn`t work

### ISSUE THREAD

**Issue by an4oys942** [jmpsec/osctrl#347]
If you deploy the project using docker-compose, then the osctrl-cli code in the container is not working

$ /opt/osctrl/bin/osctrl-cli user add --username admin --username Changeme123! --admin --environment dev
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8583df]

goroutine 1 [running]:
github.com/jmpsec/osctrl/environments.(*Environment).Get(_, {_, _})
        /home/runner/work/osctrl/osctrl/environments/environments.go:114 +0xff
main.addUser(0x0?)
        /home/runner/work/osctrl/osctrl/cli/user.go:61 +0x188
main.cliWrapper.func1(0xc0000dc480?)
        /home/runner/work/osctrl/osctrl/cli/main.go:1475 +0x4e2
github.com/urfave/cli/v2.(*Command).Run(0xc00023c480, 0xc000248b80)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5bb
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc0002344e0, 0xc0002489c0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:434 +0xc8a
github.com/urfave/cli/v2.(*Command).startApp(0xc00023c360, 0xc0002489c0)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x713
github.com/urfave/cli/v2.(*Command).Run(0xc000232280?, 0x15?)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc0002341a0, {0xc0c560?, 0xc000028088}, {0xc0000200a0, 0xa, 0xa})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb48
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/osctrl/osctrl/cli/main.go:1504 +0x1f4
$ /opt/osctrl/bin/osctrl-cli settings show
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x75d75f]

goroutine 1 [running]:
github.com/jmpsec/osctrl/settings.(*Settings).RetrieveAllValues(0x0)
        /home/runner/work/osctrl/osctrl/settings/settings.go:231 +0x5f
main.listConfiguration(0x0?)
        /home/runner/work/osctrl/osctrl/cli/settings.go:14 +0x35
main.cliWrapper.func1(0xc00027f530?)
        /home/runner/work/osctrl/osctrl/cli/main.go:1475 +0x4e2
github.com/urfave/cli/v2.(*Command).Run(0xc0002305a0, 0xc000280b00)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163 +0x5bb
github.com/urfave/cli/v2.(*App).RunAsSubcommand(0xc0001ccea0, 0xc000280980)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:434 +0xc8a
github.com/urfave/cli/v2.(*Command).startApp(0xc000230120, 0xc000280980)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:278 +0x713
github.com/urfave/cli/v2.(*Command).Run(0xa3ff60?, 0xc0001f9ef0?)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:94 +0xba
github.com/urfave/cli/v2.(*App).RunContext(0xc0001ccb60, {0xc0c560?, 0xc0000ae020}, {0xc000094150, 0x3, 0x3})
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313 +0xb48
github.com/urfave/cli/v2.(*App).Run(...)
        /home/runner/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224
main.main()
        /home/runner/work/osctrl/osctrl/cli/main.go:1504 +0x1f4

**Comment by an4oys942** [comment]
![Снимок экрана 2023-03-22 в 15 01 37](https://user-images.githubusercontent.com/59088530/226900610-9357e22c-52c6-440e-8d19-17c96b770331.png)

**Comment by vinayakdb** [comment]
You are right, I did not notice the api json file too.
However, the following is working for me using docker-compose-dev:
docker exec -u 0 -it osctrl-tls /bin/bash
osctrl-cli --db --db-file /opt/osctrl/config/db.json user add --username admin --password Changeme123! -a -n AdminUser -e mytenant

Notice the db argument.

**Comment by an4oys942** [comment]
Thank you. 
Now I am getting this error when trying to add macos node.
![Снимок экрана 2023-04-21 в 18 26 00](https://user-images.githubusercontent.com/59088530/233675633-2af78816-2a9e-4190-bce1-05812301cafc.png)

```
osctrl-tls      | 2023-04-21T14:59:00.212722571Z 2023/04/21 14:59:00 /home/runner/work/osctrl/osctrl/nodes/nodes.go:345 cannot convert [123 34 101 110 114 111 108 108 95 115 101 99 114 101 116 34 58 34 45 67 65 106 117 56 78 119 114 49 115 111 101 99 89 53 78 113 50 52 70 50 112 84 73 54 56 101 115 79 51 100 88 79 87 68 50 99 120 108 107 45 71 117 90 85 75 87 104 119 104 103 51 104 54 113 90 82 75 115 70 51 73 95 34 44 34 104 111 115 116 95 105 100 101 110 116 105 102 105 101 114 34 58 34 54 52 51 66 65 69 54 68 45 52 55 53 69 45 53 52 70 57 45 57 68 52 66 45 52 53 65 56 66 65 56 50 57 51 54 69 34 44 34 112 108 97 116 102 111 114 109 95 116 121 112 101 34 58 34 50 49 34 44 34 104 111 115 116 95 100 101 116 97 105 108 115 34 58 123 34 111 115 95 118 101 114 115 105 111 110 34 58 123 34 95 105 100 34 58 34 34 44 34 99 111 100 101 110 97 109 101 34 58 34 34 44 34 109 97 106 111 114 34 58 34 49 51 34 44 34 109 105 110 111 114 34 58 34 51 34 44 34 110 97 109 101 34 58 34 109 97 99 79 83 34 44 34 112 97 116 99 104 34 58 34 48 34 44 34 112 108 97 116 102 111 114 109 34 58 34 100 97 114 119 105 110 34 44 34 112 108 97 116 102 111 114 109 95 108 105 107 101 34 58 34 100 97 114 119 105 110 34 44 34 118 101 114 115 105 111 110 34 58 34 49 51 46 51 34 125 44 34 111 115 113 117 101 114 121 95 105 110 102 111 34 58 123 34 98 117 105 108 100 95 100 105 115 116 114 111 34 58 34 49 48 46 49 52 34 44 34 98 117 105 108 100 95 112 108 97 116 102 111 114 109 34 58 34 100 97 114 119 105 110 34 44 34 99 111 110 102 105 103 95 104 97 115 104 34 58 34 34 44 34 99 111 110 102 105 103 95 118 97 108 105 100 34 58 34 48 34 44 34 101 120 116 101 110 115 105 111 110 115 34 58 34 105 110 97 99 116 105 118 101 34 44 34 105 110 115 116 97 110 99 101 95 105 100 34 58 34 48 55 50 54 56 50 56 98 45 56 99 57 97 45 52 100 101 54 45 98 102 55 57 45 55 100 102 53 50 99 100 53 97 98 100 99 34 44 34 112 105 100 34 58 34 57 50 51 50 50 34 44 34 115 116 97 114 116 95 116 105 109 101 34 58 34 49 54 56 50 48 56 57 49 48 49 34 44 34 117 117 105 100 34 58 34 54 52 51 66 65 69 54 68 45 52 55 53 69 45 53 52 70 57 45 57 68 52 66 45 52 53 65 56 66 65 56 50 57 51 54 69 34 44 34 118 101 114 115 105 111 110 34 58 34 53 46 55 46 48 34 44 34 119 97 116 99 104 101 114 34 58 34 57 50 51 49 52 34 125 44 34 115 121 115 116 101 109 95 105 110 102 111 34 58 123 34 99 111 109 112 117 116 101 114 95 110 97 109 101 34 58 34 109 97 99 98 111 111 107 45 67 48 50 71 68 48 67 74 77 68 54 78 34 44 34 99 112 117 95 98 114 97 110 100 34 58 34 73 110 116 101 108 40 82 41 32 67 111 114 101 40 84 77 41 32 105 57 45 57 56 56 48 72 32 67 80 85 32 64 32 50 46 51 48 71 72 122 34 44 34 99 112 117 95 108 111 103 105 99 97 108 95 99 111 114 101 115 34 58 34 49 54 34 44 34 99 112 117 95 112 104 121 115 105 99 97 108 95 99 111 114 101 115 34 58 34 56 34 44 34 99 112 117 95 115 117 98 116 121 112 101 34 58 34 73 110 116 101 108 32 120 56 54 45 54 52 104 32 72 97 115 119 101 108 108 34 44 34 99 112 117 95 116 121 112 101 34 58 34 120 56 54 95 54 52 104 34 44 34 104 97 114 100 119 97 114 101 95 109 111 100 101 108 34 58 34 77 97 99 66 111 111 107 80 114 111 49 54 44 49 34 44 34 104 97 114 100 119 97 114 101 95 115 101 114 105 97 108 34 58 34 67 48 50 71 68 48 67 74 77 68 54 78 34 44 34 104 97 114 100 119 97 114 101 95 118 101 110 100 111 114 34 58 34 65 112 112 108 101 32 73 110 99 46 34 44 34 104 97 114 100 119 97 114 101 95 118 101 114 115 105 111 110 34 58 34 49 46 48 34 44 34 104 111 115 116 110 97 109 101 34 58 34 109 97 99 98 111 111 107 45 67 48 50 71 68 48 67 74 77 68 54 78 34 44 34 108 111 99 97 108 95 104 111 115 116 110 97 109 101 34 58 34 109 97 99 98 111 111 107 45 67 48 50 71 68 48 67 74 77 68 54 78 34 44 34 112 104 121 115 105 99 97 108 95 109 101 109 111 114 121 34 58 34 49 55 49 55 57 56 54 57 49 56 52 34 44 34 117 117 105 100 34 58 34 54 52 51 66 65 69 54 68 45 52 55 53 69 45 53 52 70 57 45 57 68 52 66 45 52 53 65 56 66 65 56 50 57 51 54 69 34 125 44 34 112 108 97 116 102 111 114 109 95 105 110 102 111 34 58 123 34 97 100 100 114 101 115 115 34 58 34 48 120 102 102 57 56 98 48 48 48 34 44 34 100 97 116 101 34 58 34 48 51 47 48 52 47 50 48 50 51 32 34 44 34 101 120 116 114 97 34 58 34 77 66 80 49 54 49 46 56 56 90 46 70 48 48 48 46 66 48 48 46 50 51 48 51 48 52 48 51 52 55 59 32 77 66 80 49 54 49 59 32 49 57 54 56 46 49 48 48 46 49 55 46 48 46 48 59 32 114 111 111 116 64 114 112 114 114 120 59 32 83 97 116 32 77 97 114 32 32 52 32 48 51 58 52 55 58 48 54 32 50 48 50 51 59 32 49 57 54 56 46 49 48 48 46 49 55 32 40 66 92 117 48 48 50 54 73 41 59 32 70 48 48 48 95 66 48 48 59 32 79 102 102 105 99 105 97 108 32 66 117 105 108 100 44 32 82 69 76 69 65 83 69 59 32 99 108 97 110 103 45 49 52 48 51 46 48 46 50 50 46 49 49 34 44 34 114 101 118 105 115 105 111 110 34 58 34 49 57 54 56 46 49 48 48 46 49 55 32 40 66 92 117 48 48 50 54 73 41 34 44 34 115 105 122 101 34 58 34 56 51 56 56 54 48 56 34 44 34 118 101 110 100 111 114 34 58 34 65 112 112 108 101 32 73 110 99 46 32 34 44 34 118 101 114 115 105 111 110 34 58 34 49 57 54 56 46 49 48 48 46 49 55 46 48 46 48 32 40 105 66 114 105 100 103 101 58 32 50 48 46 49 54 46 52 50 53 50 46 48 46 48 44 48 41 32 34 44 34 118 111 108 117 109 101 95 115 105 122 101 34 58 34 50 48 51 57 56 48 56 34 125 125 125] to Text
osctrl-tls      | 2023-04-21T14:59:00.212752349Z [0.592ms] [rows:0] INSERT INTO "osquery_nodes" ("created_at","updated_at","deleted_at","node_key","uuid","platform","platform_version","osquery_version","hostname","localname","ip_address","username","osquery_user","environment","cpu","memory","hardware_serial","daemon_hash","config_hash","bytes_received","raw_enrollment","last_status","last_result","last_config","last_query_read","last_query_write","user_id","environment_id","extra_data") VALUES ('2023-04-21 14:59:00.211','2023-04-21 14:59:00.211',NULL,'5ffcf231dc728fe6a6849516c7ed1c0bb2388091','643BAE6D-475E-54F9-9D4B-45A8BA82936E','darwin','13.3','5.7.0','macbook-C02GD0CJMD6N','macbook-C02GD0CJMD6N','172.30.43.16','unknown','unknown','mytenant','Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz','17179869184','C02GD0CJMD6N','','',1572,'{"enroll_secret":"-CAju8Nwr1soecY5Nq24F2pTI68esO3dXOWD2cxlk-GuZUKWhwhg3h6qZRKsF3I_","host_identifier":"643BAE6D-475E-54F9-9D4B-45A8BA82936E","platform_type":"21","host_details":{"os_version":{"_id":"","codename":"","major":"13","minor":"3","name":"macOS","patch":"0","platform":"darwin","platform_like":"darwin","version":"13.3"},"osquery_info":{"build_distro":"10.14","build_platform":"darwin","config_hash":"","config_valid":"0","extensions":"inactive","instance_id":"0726828b-8c9a-4de6-bf79-7df52cd5abdc","pid":"92322","start_time":"1682089101","uuid":"643BAE6D-475E-54F9-9D4B-45A8BA82936E","version":"5.7.0","watcher":"92314"},"system_info":{"computer_name":"macbook-C02GD0CJMD6N","cpu_brand":"Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz","cpu_logical_cores":"16","cpu_physical_cores":"8","cpu_subtype":"Intel x86-64h Haswell","cpu_type":"x86_64h","hardware_model":"MacBookPro16,1","hardware_serial":"C02GD0CJMD6N","hardware_vendor":"Apple Inc.","hardware_version":"1.0","hostname":"macbook-C02GD0CJMD6N","local_hostname":"macbook-C02GD0CJMD6N","physical_memory":"17179869184","uuid":"643BAE6D-475E-54F9-9D4B-45A8BA82936E"},"platform_info":{"address":"0xff98b000","date":"03/04/2023 ","extra":"MBP161.88Z.F000.B00.2303040347; MBP161; 1968.100.17.0.0; root@rprrx; Sat Mar  4 03:47:06 2023; 1968.100.17 (B\u0026I); F000_B00; Official Build, RELEASE; clang-1403.0.22.11","revision":"1968.100.17 (B\u0026I)","size":"8388608","vendor":"Apple Inc. ","version":"1968.100.17.0.0 (iBridge: 20.16.4252.0.0,0) ","volume_size":"2039808"}}}','0000-00-00 00:00:00','0000-00-00 00:00:00','0000-00-00 00:00:00','0000-00-00 00:00:00','0000-00-00 00:00:00',0,1,'') RETURNING "id"
osctrl-tls      | 2023-04-21T14:59:00.213204851Z handlers.go:276: error creating node Create cannot convert [123 34 101 110 114 111 108 108 95 115 101 99 114 101 116 34 58 34 45 67 65 106 117 56 78 119 114 49 115 111 101 99 89 53 78 113 50 52 70 50 112 84 73 54 56 101 115 79 51 100 88 79 87 68 50 99 120 108 107 45 71 117 90 85 75 87 104 119 104 103 51 104 54 113 90 82 75 115 70 51 73 95 34 44 34 104 111 115 116 95 105 100 101 110 116 105 102 105 101 114 34 58 34 54 52 51 66 65 69 54 68 45 52 55 53 69 45 53 52 70 57 45 57 68 52 66 45 52 53 65 56 66 65 56 50 57 51 54 69 34 44 34 112 108 97 116 102 111 114 109 95 116 121 112 101 34 58 34 50 49 34 44 34 104 111 115 116 95 100 101 116 97 105 108 115 34 58 123 34 111 115 95 118 101 114 115 105 111 110 34 58 123 34 95 105 100 34 58 34 34 44 34 99 111 100 101 110 97 109 101 34 58 34 34 44 34 109 97 106 111 114 34 58 34 49 51 34 44 34 109 105 110 111 114 34 58 34 51 34 44 34 110 97 109 101 34 58 34 109 97 99 79 83 34 44 34 112 97 116 99 104 34 58 34 48 34 44 34 112 108 97 116 102 111 114 109 34 58 34 100 97 114 119 105 110 34 44 34 112 108 97 116 102 111 114 109 95 108 105 107 101 34 58 34 100 97 114 119 105 110 34 44 34 118 101 114 115 105 111 110 34 58 34 49 51 46 51 34 125 44 34 111 115 113 117 101 114 121 95 105 110 102 111 34 58 123 34 98 117 105 108 100 95 100 105 115 116 114 111 34 58 34 49 48 46 49 52 34 44 34 98 117 105 108 100 95 112 108 97 116 102 111 114 109 34 58 34 100 97 114 119 105 110 34 44 34 99 111 110 102 105 103 95 104 97 115 104 34 58 34 34 44 34 99 111 110 102 105 103 95 118 97 108 105 100 34 58 34 48 34 44 34 101 120 116 101 110 115 105 111 110 115 34 58 34 105 110 97 99 116 105 118 101 34 44 34 105 110 115 116 97 110 99 101 95 105 100 34 58 34 48 55 50 54 56 50 56 98 45 56 99 57 97 45 52 100 101 54 45 98 102 55 57 45 55 100 102 53 50 99 100 53 97 98 100 99 34 44 34 112 105 100 34 58 34 57 50 51 50 50 34 44 34 115 116 97 114 116 95 116 105 109 101 34 58 34 49 54 56 50 48 56 57 49 48 49 34 44 34 117 117 105 100 34 58 34 54 52 51 66 65 69 54 68 45 52 55 53 69 45 53 52 70 57 45 57 68 52 66 45 52 53 65 56 66 65 56 50 57 51 54 69 34 44 34 118 101 114 115 105 111 110 34 58 34 53 46 55 46 48 34 44 34 119 97 116 99 104 101 114 34 58 34 57 50 51 49 52 34 125 44 34 115 121 115 116 101 109 95 105 110 102 111 34 58 123 34 99 111 109 112 117 116 101 114 95 110 97 109 101 34 58 34 109 97 99 98 111 111 107 45 67 48 50 71 68 48 67 74 77 68 54 78 34 44 34 99 112 117 95 98 114 97 110 100 34 58 34 73 110 116 101 108 40 82 41 32 67 111 114 101 40 84 77 41 32 105 57 45 57 56 56 48 72 32 67 80 85 32 64 32 50 46 51 48 71 72 122 34 44 34 99 112 117 95 108 111 103 105 99 97 108 95 99 111 114 101 115 34 58 34 49 54 34 44 34 99 112 117 95 112 104 121 115 105 99 97 108 95 99 111 114 101 115 34 58 34 56 34 44 34 99 112 117 95 115 117 98 116 121 112 101 34 58 34 73 110 116 101 108 32 120 56 54 45 54 52 104 32 72 97 115 119 101 108 108 34 44 34 99 112 117 95 116 121 112 101 34 58 34 120 56 54 95 54 52 104 34 44 34 104 97 114 100 119 97 114 101 95 109 111 100 101 108 34 58 34 77 97 99 66 111 111 107 80 114 111 49 54 44 49 34 44 34 104 97 114 100 119 97 114 101 95 115 101 114 105 97 108 34 58 34 67 48 50 71 68 48 67 74 77 68 54 78 34 44 34 104 97 114 100 119 97 114 101 95 118 101 110 100 111 114 34 58 34 65 112 112 108 101 32 73 110 99 46 34 44 34 104 97 114 100 119 97 114 101 95 118 101 114 115 105 111 110 34 58 34 49 46 48 34 44 34 104 111 115 116 110 97 109 101 34 58 34 109 97 99 98 111 111 107 45 67 48 50 71 68 48 67 74 77 68 54 78 34 44 34 108 111 99 97 108 95 104 111 115 116 110 97 109 101 34 58 34 109 97 99 98 111 111 107 45 67 48 50 71 68 48 67 74 77 68 54 78 34 44 34 112 104 121 115 105 99 97 108 95 109 101 109 111 114 121 34 58 34 49 55 49 55 57 56 54 57 49 56 52 34 44 34 117 117 105 100 34 58 34 54 52 51 66 65 69 54 68 45 52 55 53 69 45 53 52 70 57 45 57 68 52 66 45 52 53 65 56 66 65 56 50 57 51 54 69 34 125 44 34 112 108 97 116 102 111 114 109 95 105 110 102 111 34 58 123 34 97 100 100 114 101 115 115 34 58 34 48 120 102 102 57 56 98 48 48 48 34 44 34 100 97 116 101 34 58 34 48 51 47 48 52 47 50 48 50 51 32 34 44 34 101 120 116 114 97 34 58 34 77 66 80 49 54 49 46 56 56 90 46 70 48 48 48 46 66 48 48 46 50 51 48 51 48 52 48 51 52 55 59 32 77 66 80 49 54 49 59 32 49 57 54 56 46 49 48 48 46 49 55 46 48 46 48 59 32 114 111 111 116 64 114 112 114 114 120 59 32 83 97 116 32 77 97 114 32 32 52 32 48 51 58 52 55 58 48 54 32 50 48 50 51 59 32 49 57 54 56 46 49 48 48 46 49 55 32 40 66 92 117 48 48 50 54 73 41 59 32 70 48 48 48 95 66 48 48 59 32 79 102 102 105 99 105 97 108 32 66 117 105 108 100 44 32 82 69 76 69 65 83 69 59 32 99 108 97 110 103 45 49 52 48 51 46 48 46 50 50 46 49 49 34 44 34 114 101 118 105 115 105 111 110 34 58 34 49 57 54 56 46 49 48 48 46 49 55 32 40 66 92 117 48 48 50 54 73 41 34 44 34 115 105 122 101 34 58 34 56 51 56 56 54 48 56 34 44 34 118 101 110 100 111 114 34 58 34 65 112 112 108 101 32 73 110 99 46 32 34 44 34 118 101 114 115 105 111 110 34 58 34 49 57 54 56 46 49 48 48 46 49 55 46 48 46 48 32 40 105 66 114 105 100 103 101 58 32 50 48 46 49 54 46 52 50 53 50 46 48 46 48 44 48 41 32 34 44 34 118 111 108 117 109 101 95 115 105 122 101 34 58 34 50 48 51 57 56 48 56 34 125 125 125] to Text
osctrl-nginx    | 2023-04-21T14:59:00.215282341Z 172.30.43.16 - - [21/Apr/2023:14:59:00 +0000] "POST /e1149eb3-fd81-46e7-bee8-a9a67b8d7356/enroll HTTP/1.1" 200 75 "-" "osquery/5.7.0"
osctrl-tls      | 2023-04-21T14:59:00.257035349Z handlers.go:489: GetByKey record not found
osctrl-tls      | 2023-04-21T14:59:00.257128244Z 
osctrl-tls      | 2023-04-21T14:59:00.257146458Z 2023/04/21 14:59:00 /home/runner/work/osctrl/osctrl/nodes/nodes.go:162 record not found
osctrl-tls      | 2023-04-21T14:59:00.257151600Z [0.540ms] [rows:0] SELECT * FROM "osquery_nodes" WHERE node_key = '5ffcf231dc728fe6a6849516c7ed1c0bb2388091' AND "osquery_nodes"."deleted_at" IS NULL ORDER BY "osquery_nodes"."id" LIMIT 1
```

**Comment by javuto** [comment]
Please take a look at the latest commits in https://github.com/jmpsec/osctrl/pull/341, it may help solve some of the docker issues. Thank you!

**Comment by javuto** [comment]
The `docker-dev` environment has been updated and many issues fixed. Please test it and if the issues persist, feel free to open a new issue. Thanks!

https://github.com/jmpsec/osctrl/pull/393
